---
- hosts: app
  remote_user: root
  become: true
  handlers:
    - name: reload crudtest
      shell: sudo /etc/init.d/crudtest stop && sudo /etc/init.d/crudtest start

  tasks:
  - name: prepare dir
    file: path={{ project_dir }} mode=0777 state=directory

  - name: pull app
    git: repo={{ project_repo }} dest={{ project_root }} version={{ branch }} force=yes

  - name: install deps
    shell: npm install
    args:
      chdir: "{{project_root}}"

  - name: Create Crudtest service
    template: src=templates/daemon.j2 dest=/etc/init.d/crudtest group=root owner=root mode=0777
    tags: 'config'
    notify:
      - reload crudtest

  - name: reload crudtest
    shell: /etc/init.d/crudtest stop && /etc/init.d/crudtest start
    become_user: root
    become: true
