language: node_js
node_js:
  - 5.10.1

addons:
  postgresql: '9.4'

notifications:
  slack: devops-training-spb:WMoTNpq308zIwHDNZj8xttd6

before_script:
  createuser -s crudtest
  psql postgres -c 'create database crudtest'
  psql postgres -c "ALTER ROLE crudtest WITH PASSWORD 'crudtest';"
