# sudo: false
language: node_js
node_js: '6.1'
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
# notifications:
#   slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  provider: heroku
  api_key:
    secure: PnGuL5CgQZ/Yx0v9MJ72csA4Mjf5YWbeX/blM6UxzPXZD9oSmqmLtdGEIsBtlnXWrhZHq9GOAEnL42vWVs17n/M4YZvVi8jblGwLm2dnyKgW4YuIAHHPBtNR8ctjNuS0P00/+N1S83stumRjXrfbZBb9ZtXUBZ3dIu/fO1lr1FrIOjLtvUaYx2c9u51it0T7PO1h7NDDAFf5BpChinVi3qgEIy+9RnBLhAIHiavYXvzO8c32ahK0Cbsd7kq9ehF7M3nmYD2v2mJf2ZyQsD7ljtOqfYtUGKsbrVnRGkcDg5iuNwTsiCyzxm+3YOKQmZARULmzHXotKNZe67lEXeuDQNkQCfjr1XLQplU3kYApr26sAKA4AVSCSn1MBm9EP4E4lcg1SHwQ0VYscTvKEbV2bsdr7ByJEQxGq1PfSsgq4y0OR5bPWPqh7X1Dw9EGtRzUXuIhOnNcqIV9GdbJeAlxJyJqjSdpuohpaBvNBBgXbqDa/IrQjURX+ZYGrO2jF70yezR9jozc2NkFtWv6iEr0B0vKB3JzKRTOJ5ZB5HpXISBtXwRLV0KFcPHsB1w7LwgfqfKEMtr6pns84hUkFGqPmnW+Ns2kmx6OnMlxTzJMMLcpSQj8mfKR/8jEqIYH7K4Vo9TzM9WJpFpJG1EbzReIqELFkz0odds6fhC/4KB2P/8=
  app: fierce-depths-58786
  on:
    repo: k-zelenkov/delivery-pipeline-training
