version: '2'
services:
  # Node exporter, Grafana, Prometheus
  grafana:
    image: grafana/grafana
    links: 
      - "prometheus"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    links: 
      - "node-exporter"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - node-exporter
  
  node-exporter:
    image: tray/node_exporter
    ports:
      - "9100:9100"
